### ISSUE TITLE
Meeting poing

### ISSUE THREAD

**Issue by gortazar** [mcisnerosb57/Proyecto#1]
Si ves este issue es que estamos en el mismo barco :) Contesta para saber que has llegado hasta aquí.

**Comment by mcisnerosb57** [comment]
Si me ha llegado. Perfecto entonces. Entonces espero los logs de errores
para ir mirando lo de la red neuronal. Saludos

**Comment by gortazar** [comment]
Ok.

**Comment by mcisnerosb57** [comment]
Patxi , buenos dias. Tengo varias preguntas con el TFG en general.
¿Puedo presentar el TFG en cualquier momento?,?. o hay unas fechas
especificas para entregarlo, y presentarlo.Si es asi, ¿dónde puedo ver las
fechas?.
¿Hay que tener todas las asignaturas aprobadas para poder presentarlo?
¿Se puede hacer el proyecto con otra persona de distinta titulacion?. Por
ejemplo de Ingenieria de computadores.

Gracias de antemano, saludos.

2016-09-01 17:06 GMT+02:00 Francisco Gortázar notifications@github.com:
